const mashup = [
  {
    id: "1",
    favourite: false,
    songName: "Sanam Re",
    Artist: "Mithoon & Arjit Singh",
    song: "Mashup/Sanam Re.mp3",
    imgsrc: "img1/sanam re.jpg",
    listen: "107,48,767",
    duration: "5:08",
  },
  {  id: "2",
    favourite: false,
    songName: "Her",
    Artist: "Mashup studio",
    song: "Mashup/Her.mp3",
    imgsrc: "img/11.jpg",
    listen: "7,86,8776",
    duration: "2:59",
  },
  {
    id: "3",
    favourite: false,
    songName: "Love Dose",
    Artist: "Yo Yo Honey singh",
    song: "Mashup/Love Dose.mp3",
    imgsrc: "img/honey.jpg",
    listen: "367,98,097",
    duration: "3:48",
  },
  {
    id: "4",
    favourite: false,
    songName: "Lut Gaye",
    Artist: "Jubin Nuatiyal",
    song: "Mashup/Lut Gaye.mp3",
    imgsrc: "img1/Lut Gaye.jpg",
    listen: "17,48,767",
    duration: "3:48",
  },
  {
    id: "5",
    favourite: false,
    songName: "Nazar",
    Artist: "Pulki&Kabir ",
    song: "Mashup/Nazar.mp3",
    imgsrc: "img1/nazar.jpg",
    listen: "177,48,767",
    duration: "3:27",
  },
  {
    id: "6",
    favourite: false,
    songName: "No-Love",
    Artist: "Shubh",
    song: "Mashup/No-Love.mp3",
    imgsrc: "img1/no love.jpg",
    listen: "123,748,767",
    duration: "2:50",
  },
  // {
  //   id: "7",
  //   favourite: false,
  //   songName: "Prada",
  //   Artist: "",
  //   song: "Mashup/Prada.mp3",
  //   imgsrc: "img1/Prada.jpg",
  //   listen: "737,08,767",
  //   duration: "3:05",
  // },
 
  // {
  //   id: "9",
  //   favourite: false,
  //   songName: "Shape",
  //   Artist: "KaKa",
  //   song: "Mashup/Shape.mp3",
  //   imgsrc: "img1/shape.jpg",
  //   listen: "179,97,078",
  //   duration: "3:17",
  // },
  // {
  //   id: "10",
  //   favourite: false,
  //   songName: "So High",
  //   Artist: "Sidhu Moosewala",
  //   song: "Mashup/So High.mp3",
  //   imgsrc: "img1/So High.jpg",
  //   listen: "789,88,887",
  //   duration: "3:38",
  // },
  // {
  //   id: "10",
  //   favourite: false,
  //   songName: "Temporary Pyar",
  //   Artist: "KAKA",
  //   song: "Mashup/Temporary Pyar.mp3",
  //   imgsrc: "img1/shape.jpg",
  //   listen: "345,88,887",
  //   duration: "4:19",
  // },
  // {
  //   id: "11",
  //   favourite: false,
  //   songName: "Tera Mera Viah",
  //   Artist: "Jass Manak",
  //   song: "Mashup/Tera Mera Viah.mp3",
  //   imgsrc: "img1/tera mera viah.jpg",
  //   listen: "875,12,234",
  //   duration: "3:15",
  // },
  // {
  //   id: "12",
  //   favourite: false,
  //   songName: "These Days ",
  //   Artist: "Bohemia & Sidhu ",
  //   song: "Mashup/These Days Full.mp3",
  //   imgsrc: "img1/these days.jpg",
  //   listen: "235,19,734",
  //   duration: "3:31",
  // },
  // {
  //   id: "13",
  //   favourite: false,
  //   songName: "Titliaan",
  //   Artist: "Hardy Sandhu",
  //   song: "Mashup/Titliaan.mp3",
  //   imgsrc: "img1/titliyan.jpg",
  //   listen: "876,35,234",
  //   duration: "3:15",
  // },
  // {
  //   id: "14",
  //   favourite: false,
  //   songName: "We Rollin",
  //   Artist: "Shubh",
  //   song: "Mashup/We Rollin.mp3",
  //   imgsrc: "img1/Rollin.jpg",
  //   listen: "076,35,234",
  //   duration: "3:19",
  // },

];

export { mashup };
